### ISSUE TITLE
Call to undefined method Doctrine\ODM\PHPCR\DocumentManager::transactional()

### ISSUE THREAD

**Issue by delportd** [symfony-cmf/symfony-cmf#217]
Hi !

I'm using this good CMF for the second time, but when I try to load the fixtures with "php app/console doctrine:phpcr:fixtures:load" to initialise the project (as they say in the documentation http://symfony.com/doc/master/cmf/book/installation.html) it fails.

The error : 
```bash
root@56d55021afb3:/var/www# php app/console doctrine:phpcr:fixtures:load
Careful, database will be purged. Do you want to continue Y/N ?y
PHP Fatal error:  Call to undefined method Doctrine\ODM\PHPCR\DocumentManager::transactional() in /var/www/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/PHPCRExecutor.php on line 63
                                                                       
  [Symfony\Component\Debug\Exception\UndefinedMethodException]                             
  Attempted to call method "transactional" on class "Doctrine\ODM\PHPCR\DocumentManager".  

doctrine:phpcr:fixtures:load [--fixtures[="..."]] [--append] [--name[="..."]] [--no-initialize] [--session[="..."]] [--dm[="..."]]
```

My parameters.yml
```
parameters:
    database_driver: pdo_mysql
    database_host: 172.17.0.50
    database_port: 3306
    database_name: symfony2
    database_user: root
    database_password: PYNhXClUoAZMWxgAY5mfScd5Kvcf3m
    database_path: null
    phpcr_backend:
        type: doctrinedbal
        connection: default
        caches:
            meta: doctrine_cache.providers.phpcr_meta
            nodes: doctrine_cache.providers.phpcr_nodes
    phpcr_workspace: default
    phpcr_user: admin
    phpcr_password: admin
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: Bv8sL3G1OsNazsKyftEmFXwds8RcBr
    debug_toolbar: true
    debug_redirects: false
    use_assetic_controller: true
```

The thing was working yesterday (I'm seting up an dev environment in docker) I didn't changed anything to my Dockerfiles, so I think the problem may be coming from some vendor library (maybe doctrine/data-fixtures) ?

The CMF was working with : 
```
"name": "doctrine/data-fixtures",
            "version": "v1.0.1",
```
But not anymore with : 
```
"name": "doctrine/data-fixtures",
            "version": "v1.1.0",
```

Thank you,
A french guy.
