### ISSUE TITLE
Attempted to load class "SimpleChoiceList" from namespace "Symfony\Component\Form\Extension\Core\ChoiceList".

### ISSUE THREAD

**Issue by samanmohamadi** [symfony-cmf/symfony-cmf#234]
Hi 
I attempt to add new document name article so I add the following codes.
But I encouneter this error when trying to create new article:
`Attempted to load class "SimpleChoiceList" from namespace "Symfony\Component\Form\Extension\Core\ChoiceList"`.

```
<?php

namespace AppBundle\Document;

use Doctrine\ODM\PHPCR\Mapping\Annotations as PHPCR;
use Symfony\Cmf\Bundle\ContentBundle\Doctrine\Phpcr\StaticContentBase;


/**
 * @PHPCR\Document()
 */
class Article extends  StaticContentBase
{
    /**
     * @PHPCR\Field(type="string")
     */
    protected $preface;

    /**
     * @return mixed
     */
    public function getPreface()
    {
        return $this->preface;
    }

    /**
     * @param mixed $preface
     */
    public function setPreface($preface)
    {
        $this->preface = $preface;
    }
}
```

```
<?php

namespace AppBundle\Admin;

use Sonata\AdminBundle\Form\FormMapper;
use Sonata\DoctrinePHPCRAdminBundle\Form\Type\TreeModelType;
use Symfony\Cmf\Bundle\ContentBundle\Admin\StaticContentAdmin as BaseAdmin;

class ArticleAdmin extends BaseAdmin
{



    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('preface', TreeModelType::class)
            ->end()
        ;
    }

}
```

```
services:
    app.admin.article:
        class: AppBundle\Admin\ArticleAdmin
        arguments:
            - ''
            - AppBundle\Document\Article
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Basic CMS', label: 'articles' }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]
```
