### ISSUE TITLE
Bundles updates to create recipes for Flex

### ISSUE THREAD

**Issue by covex-nn** [symfony-cmf/symfony-cmf#260]
I made some updates for core, block, menu and content bundles:

* https://github.com/covex-nn/core-bundle/compare/master...updates
* https://github.com/covex-nn/block-bundle/compare/master...updates
* https://github.com/covex-nn/menu-bundle/compare/master...updates
* https://github.com/covex-nn/content-bundle/compare/master...updates

With these changes each bundle can be installed separately with Symfony Flex without errors. And each bundle can have a default configuration (a recipe!) like this or none:

```yaml
cmf_core:
    persistence:
        phpcr:
            enabled: true
```

If all bundles will be combined together with `doctrine/phpcr-bundle` (i.e. `symfony-cmf/symfony-cmf` without `doctrine/phpcr-odm`) they also can be installed with Symfony Flex without error, a minimum default configuration for such `pack` is here:

```yaml
cmf_routing:
    dynamic:
        persistence:
            phpcr:
                enabled: true
```

Also i created a [gist](https://gist.github.com/covex-nn/a001b92c4f5911076934585704eef1fc) to see how it works. You need to create a `composer.json`, run `composer install`, see error message, create a default configuration, run `composer auto-scripts`, see no errors.

Next, there could be created packs for each `jackalope/jackalope-transport` package. Such pack should require `doctrine/phpcr-bundle`, `doctrine/phpcr-odm`, `jackalope/jackalope-transport` implementation, and `phpcr/phpcr-implementation` implementation. There are [5 of them](https://packagist.org/providers/jackalope/jackalope-transport) in packagist.org. I hope such packages can have default configuration to have a recipe.

What do you think? If my changes are ok, a will create 4 PRs

**Comment by dbu** [comment]
this looks very good to me! afaik @ElectricMaxxx played around with a travis test that would ensure each bundle can be installed with flex without error - is that right? if we can run some travis build step that adds the bundle being tested into a flex project, we will be sure that no regressions occur.

regarding packs: 
* jackalope-transport is only to model the dependency of the core jackalope/jackalope on a transport layer. in the end, jackalope&transport _is_ a phpcr-implementation. looking at the packagist numbers, only dbal and jackrabbit matter. the others are all experimental and incomplete, and nobody has been working on them for ages. i think having a phpcr-dbal and a phpcr-jackrabbit pack (with phpcr-odm, the phpcr-bundle and the right transport) for those 2 is enough in that part.

what exactly would the symfony-cmf-without-odm-pack be? with orm? or without any storage? if the later, could we call that symfony-cmf-without-storage? it would be non-functional out of the box, i am not sure if there is value to it. maybe symfony-cmf-phpcr-dbal and symfony-cmf-phpcr-jackrabbit that depend on their respective phpcr packs? plus possibly a symfony-cmf-orm pack

**Comment by covex-nn** [comment]
Actualy only `symfony-cmf/content-bundle` cannot be installed without errors. Others can be installed with flex only when there is no any configuration for that bundles (not all, but some of them).

To see a error of content-bundle, run `composer create-project symfony/skeleton .`, then add this to `require` section and run `composer update`:

```yaml
        "symfony-cmf/content-bundle": "2.1.x-dev",
        "symfony-cmf/core-bundle": "2.1.x-dev",
        "symfony-cmf/menu-bundle": "2.2.x-dev",
        "symfony-cmf/routing": "2.1.x-dev",
        "symfony-cmf/routing-bundle": "2.1.x-dev",
```

You will see this error message:

> In CmfRoutingExtension.php line 132:
> When the dynamic router is enabled, you need to either enable one of the persistence layers or set the cmf_routing.dynamic.route_provider_service_id option

To fix this i decided to add a default configuration (a recipe) for content-bundle. And if i configured content-bundle, i decided to configure all other bundles with similar recipe too. Place this yaml somewhere to `config/packages/`:

```yaml
cmf_core:
    persistence:
        phpcr:
            enabled: true

cmf_menu:
    persistence:
        phpcr:
            enabled: true

cmf_content:
    persistence:
        phpcr:
            enabled: true
```

Now if you will run `cache:clear`, you will see different error:

> In ContainerBuilder.php line 978:
> You have requested a non-existent service "validator.builder".

So, step by step i changed bundles while (1) i cannot execute `cache:clear` for a bundle and (2) i cannot execute `cache:clear` for a pack with all bundles and `doctrine/phpcr-bundle` (a symfony-cmf-without-odm-pack! bad naming, yes =)

> what exactly would the symfony-cmf-without-odm-pack be?

It is `symfony-cmf/symfony-cmf` without `doctrine/phpcr-odm`, see [composer.json](https://gist.github.com/covex-nn/a001b92c4f5911076934585704eef1fc) from my gist. This pack can have a recipe too, see [config/packages/cmf.yaml](https://gist.github.com/covex-nn/a001b92c4f5911076934585704eef1fc).

This pack will be without any storage, yes; it cannot be functionalal, but it can be configured with a recipe. This pack with a pack for `jackalope/jackalope-transport` imlementation and it's recipe will be a SymfonyCMF.

**Comment by covex-nn** [comment]
My [gist](https://gist.github.com/covex-nn/a001b92c4f5911076934585704eef1fc) contain composer.json for `symfony-cmf-without-doctrine-phpcr-odm`, recipes for all bundles and a recipe for `symfony-cmf-without-doctrine-phpcr-odm` pack

**Comment by covex-nn** [comment]
> if we can run some travis build step that adds the bundle being tested into a flex project, we will be sure that no regressions occur.

A default configuration (a recipe) should be stored somewhere to test installation with Flex, and then, after a recipe will be created this recipe could be also downloaded from `symfony/recipes-contrib`

**Comment by covex-nn** [comment]
I was wrong, i guess =(

To make `block-bundle`, `menu-bundle` and `content-bundle` installable with Symfony Flex `doctrine_phpcr.odm.default_document_manager` service must exist! `DoctrinePHPCRBundle` creates it when phpcr-odm is activated via the following configuration:

```yaml
# should it be a recipe for `doctrine/phpcr-odm`?
doctrine_phpcr:
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: true
```

May be `doctrine/phpcr-odm` should not require `phpcr/phpcr-implementation`, i will investigate
